# Use an official Python runtime as a base image
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /app

# Copy requirements file and install dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Create a certs folder for certs
RUN mkdir -p /app/certs

# Copy the app code
COPY . .

# Command to run the app
CMD ["uvicorn", "--host", "0.0.0.0", "--port", "443", "--ssl-certfile", "/app/certs/fullchain.pem", "--ssl-keyfile", "/app/certs/privkey.pem", "main:create_api"]
