SELECT * FROM customer;
SELECT * FROM public.order;
SELECT * FROM order_item;
SELECT * FROM bag;
SELECT * FROM item;
SELECT * FROM preselection;
SELECT * FROM shipment;
SELECT * FROM shipping_method;
SELECT * FROM coupon;
SELECT * FROM inventory ORDER BY id;
SELECT * FROM inventory_transaction;

DROP TABLE order_item cascade;
DROP TABLE public.order cascade;
DROP TABLE customer cascade;
DROP TABLE shipment cascade;
DROP TABLE shipping_method cascade;
DROP TABLE inventory_transaction cascade;
DROP TABLE inventory cascade;
DROP TABLE coupon cascade;
DROP TABLE preselection cascade;
DROP TABLE item cascade;
DROP TABLE bag cascade;
Truncate alembic_version;

INSERT INTO bag (id, image_url, video_url, name, description, price) VALUES (1, 'https://giftoz.netlify.app/images/custom/bag1.jpeg', 'https://www.w3schools.com/html/mov_bbb.mp4', 'bag1', 'bag', 1);
INSERT INTO bag (id, image_url, video_url, name, description, price) VALUES (2, 'https://giftoz.netlify.app/images/custom/bag2.jpeg', 'https://www.w3schools.com/html/mov_bbb.mp4', 'bag2', 'bag', 1);
INSERT INTO bag (id, image_url, video_url, name, description, price) VALUES (3, 'https://giftoz.netlify.app/images/custom/bag3.jpeg', 'https://www.w3schools.com/html/mov_bbb.mp4', 'bag3', 'bag', 1);
INSERT INTO bag (id, image_url, video_url, name, description, price) VALUES (4, 'https://giftoz.netlify.app/images/custom/bag4.jpeg', 'https://www.w3schools.com/html/mov_bbb.mp4', 'bag4', 'bag', 1);
INSERT INTO bag (id, image_url, video_url, name, description, price) VALUES (5, 'https://giftoz.netlify.app/images/custom/bag5.jpeg', 'https://www.w3schools.com/html/mov_bbb.mp4', 'bag5', 'bag', 1);

INSERT INTO item (id, image_url, video_url, product, name, description, price) VALUES (1, 'https://giftoz.netlify.app/images/custom/bricks1.jpeg', 'https://www.w3schools.com/html/mov_bbb.mp4', 'bricks', 'bricks1', 'bricks', 2.5);
INSERT INTO item (id, image_url, video_url, product, name, description, price) VALUES (2, 'https://giftoz.netlify.app/images/custom/bricks2.jpeg', 'https://www.w3schools.com/html/mov_bbb.mp4', 'bricks', 'bricks2', 'bricks', 2.5);
INSERT INTO item (id, image_url, video_url, product, name, description, price) VALUES (3, 'https://giftoz.netlify.app/images/custom/bricks3.jpeg', 'https://www.w3schools.com/html/mov_bbb.mp4', 'bricks', 'bricks3', 'bricks', 2.5);
INSERT INTO item (id, image_url, video_url, product, name, description, price) VALUES (4, 'https://giftoz.netlify.app/images/custom/bricks4.jpeg', 'https://www.w3schools.com/html/mov_bbb.mp4', 'bricks', 'bricks4', 'bricks', 2.5);
INSERT INTO item (id, image_url, video_url, product, name, description, price) VALUES (5, 'https://giftoz.netlify.app/images/custom/bricks5.jpeg', 'https://www.w3schools.com/html/mov_bbb.mp4', 'bricks', 'bricks5', 'bricks', 2.5);
INSERT INTO item (id, image_url, video_url, product, name, description, price) VALUES (6, 'https://giftoz.netlify.app/images/custom/bricks6.jpeg', 'https://www.w3schools.com/html/mov_bbb.mp4', 'bricks', 'bricks6', 'bricks', 2.5);
INSERT INTO item (id, image_url, video_url, product, name, description, price) VALUES (7, 'https://giftoz.netlify.app/images/custom/bricks7.jpeg', 'https://www.w3schools.com/html/mov_bbb.mp4', 'bricks', 'bricks7', 'bricks', 2.5);
INSERT INTO item (id, image_url, video_url, product, name, description, price) VALUES (8, 'https://giftoz.netlify.app/images/custom/bricks8.jpeg', 'https://www.w3schools.com/html/mov_bbb.mp4', 'bricks', 'bricks8', 'bricks', 2.5);
INSERT INTO item (id, image_url, video_url, product, name, description, price) VALUES (9, 'https://giftoz.netlify.app/images/custom/bricks9.jpeg', 'https://www.w3schools.com/html/mov_bbb.mp4', 'bricks', 'bricks9', 'bricks', 2.5);
INSERT INTO item (id, image_url, video_url, product, name, description, price) VALUES (10, 'https://giftoz.netlify.app/images/custom/bricks10.jpeg', 'https://www.w3schools.com/html/mov_bbb.mp4', 'bricks', 'bricks10', 'bricks', 2.5);
INSERT INTO item (id, image_url, video_url, product, name, description, price) VALUES (11, 'https://giftoz.netlify.app/images/custom/bricks11.jpeg', 'https://www.w3schools.com/html/mov_bbb.mp4', 'bricks', 'bricks11', 'bricks', 2.5);
INSERT INTO item (id, image_url, video_url, product, name, description, price) VALUES (12, 'https://giftoz.netlify.app/images/custom/design_ruler1.jpeg', 'https://www.w3schools.com/html/mov_bbb.mp4', 'design_ruler', 'design ruler1', 'design ruler', 1);
INSERT INTO item (id, image_url, video_url, product, name, description, price) VALUES (13, 'https://giftoz.netlify.app/images/custom/design_ruler2.jpeg', 'https://www.w3schools.com/html/mov_bbb.mp4', 'design_ruler', 'design ruler2', 'design ruler', 1);
INSERT INTO item (id, image_url, video_url, product, name, description, price) VALUES (14, 'https://giftoz.netlify.app/images/custom/design_ruler3.jpeg', 'https://www.w3schools.com/html/mov_bbb.mp4', 'design_ruler', 'design ruler3', 'design ruler', 1);
INSERT INTO item (id, image_url, video_url, product, name, description, price) VALUES (15, 'https://giftoz.netlify.app/images/custom/design_ruler4.jpeg', 'https://www.w3schools.com/html/mov_bbb.mp4', 'design_ruler', 'design ruler4', 'design ruler', 1);
INSERT INTO item (id, image_url, video_url, product, name, description, price) VALUES (16, 'https://giftoz.netlify.app/images/custom/id_holder1.jpeg', 'https://www.w3schools.com/html/mov_bbb.mp4', 'id_holder', 'id holder1', 'id holder', 2.5);
INSERT INTO item (id, image_url, video_url, product, name, description, price) VALUES (17, 'https://giftoz.netlify.app/images/custom/id_holder2.jpeg', 'https://www.w3schools.com/html/mov_bbb.mp4', 'id_holder', 'id holder2', 'id holder', 2.5);
INSERT INTO item (id, image_url, video_url, product, name, description, price) VALUES (18, 'https://giftoz.netlify.app/images/custom/id_holder3.jpeg', 'https://www.w3schools.com/html/mov_bbb.mp4', 'id_holder', 'id holder3', 'id holder', 2.5);
INSERT INTO item (id, image_url, video_url, product, name, description, price) VALUES (19, 'https://giftoz.netlify.app/images/custom/id_holder4.jpeg', 'https://www.w3schools.com/html/mov_bbb.mp4', 'id_holder', 'id holder4', 'id holder', 2.5);
INSERT INTO item (id, image_url, video_url, product, name, description, price) VALUES (20, 'https://giftoz.netlify.app/images/custom/id_holder5.jpeg', 'https://www.w3schools.com/html/mov_bbb.mp4', 'id_holder', 'id holder5', 'id holder', 2.5);
INSERT INTO item (id, image_url, video_url, product, name, description, price) VALUES (21, 'https://giftoz.netlify.app/images/custom/id_holder6.jpeg', 'https://www.w3schools.com/html/mov_bbb.mp4', 'id_holder', 'id holder6', 'id holder', 2.5);
INSERT INTO item (id, image_url, video_url, product, name, description, price) VALUES (22, 'https://giftoz.netlify.app/images/custom/pencil_sharpener1.jpeg', 'https://www.w3schools.com/html/mov_bbb.mp4', 'pencil_sharpener', 'pencil sharpener1', 'pencil sharpener', 3);
INSERT INTO item (id, image_url, video_url, product, name, description, price) VALUES (23, 'https://giftoz.netlify.app/images/custom/pencil_sharpener2.jpeg', 'https://www.w3schools.com/html/mov_bbb.mp4', 'pencil_sharpener', 'pencil sharpener2', 'pencil sharpener', 3);
INSERT INTO item (id, image_url, video_url, product, name, description, price) VALUES (24, 'https://giftoz.netlify.app/images/custom/bracelet1.jpeg', 'https://www.w3schools.com/html/mov_bbb.mp4', 'bracelet', 'bracelet1', 'bracelet', 2);
INSERT INTO item (id, image_url, video_url, product, name, description, price) VALUES (25, 'https://giftoz.netlify.app/images/custom/bracelet2.jpeg', 'https://www.w3schools.com/html/mov_bbb.mp4', 'bracelet', 'bracelet2', 'bracelet', 2);
INSERT INTO item (id, image_url, video_url, product, name, description, price) VALUES (26, 'https://giftoz.netlify.app/images/custom/squishy1.jpeg', 'https://www.w3schools.com/html/mov_bbb.mp4', 'squishy', 'squishy1', 'squishy', 1);
INSERT INTO item (id, image_url, video_url, product, name, description, price) VALUES (27, 'https://giftoz.netlify.app/images/custom/squishy2.jpeg', 'https://www.w3schools.com/html/mov_bbb.mp4', 'squishy', 'squishy2', 'squishy', 1);
INSERT INTO item (id, image_url, video_url, product, name, description, price) VALUES (28, 'https://giftoz.netlify.app/images/custom/squishy3.jpeg', 'https://www.w3schools.com/html/mov_bbb.mp4', 'squishy', 'squishy3', 'squishy', 1);
INSERT INTO item (id, image_url, video_url, product, name, description, price) VALUES (29, 'https://giftoz.netlify.app/images/custom/squishy4.jpeg', 'https://www.w3schools.com/html/mov_bbb.mp4', 'squishy', 'squishy4', 'squishy', 1);
INSERT INTO item (id, image_url, video_url, product, name, description, price) VALUES (30, 'https://giftoz.netlify.app/images/custom/squishy5.jpeg', 'https://www.w3schools.com/html/mov_bbb.mp4', 'squishy', 'squishy5', 'squishy', 1);
INSERT INTO item (id, image_url, video_url, product, name, description, price) VALUES (31, 'https://giftoz.netlify.app/images/custom/squishy6.jpeg', 'https://www.w3schools.com/html/mov_bbb.mp4', 'squishy', 'squishy6', 'squishy', 1);

INSERT INTO preselection (id, image_url, name, gender, description, price, bag_id, item_ids) VALUES (1, 'https://giftoz.netlify.app/images/preselections/preselection1.jpeg', 'preselection1', 'girls', 'Preselection gift bag 1', 11, 2, '{22, 20, 27, 2, 12}');
INSERT INTO preselection (id, image_url, name, gender, description, price, bag_id, item_ids) VALUES (2, 'https://giftoz.netlify.app/images/preselections/preselection2.jpeg', 'preselection2', 'boys', 'Preselection gift bag 2', 12, 4, '{23, 19, 8, 13, 24}');
INSERT INTO preselection (id, image_url, name, gender, description, price, bag_id, item_ids) VALUES (3, 'https://giftoz.netlify.app/images/preselections/preselection3.jpeg', 'preselection3', 'boys', 'Preselection gift bag 3', 12, 1, '{23, 16, 28, 7, 25}');
INSERT INTO preselection (id, image_url, name, gender, description, price, bag_id, item_ids) VALUES (4, 'https://giftoz.netlify.app/images/preselections/preselection4.jpeg', 'preselection4', 'girls', 'Preselection gift bag 4', 11, 5, '{22, 18, 29, 2, 12}');
INSERT INTO preselection (id, image_url, name, gender, description, price, bag_id, item_ids) VALUES (5, 'https://giftoz.netlify.app/images/preselections/preselection5.jpeg', 'preselection5', 'girls', 'Preselection gift bag 5', 10, 3, '{21, 26, 10, 14, 25}');

INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (1, 'bag', 1, 500, 50);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (2, 'bag', 2, 500, 50);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (3, 'bag', 3, 500, 50);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (4, 'bag', 4, 500, 50);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (5, 'bag', 5, 500, 50);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (6, 'item', 1, 100, 10);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (7, 'item', 2, 100, 10);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (8, 'item', 3, 100, 10);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (9, 'item', 4, 100, 10);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (10, 'item', 5, 100, 10);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (11, 'item', 6, 100, 10);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (12, 'item', 7, 100, 10);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (13, 'item', 8, 100, 10);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (14, 'item', 9, 100, 10);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (15, 'item', 10, 100, 10);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (16, 'item', 11, 100, 10);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (17, 'item', 12, 100, 10);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (18, 'item', 13, 100, 10);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (19, 'item', 14, 100, 10);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (20, 'item', 15, 100, 10);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (21, 'item', 16, 100, 10);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (22, 'item', 17, 100, 10);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (23, 'item', 18, 100, 10);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (24, 'item', 19, 100, 10);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (25, 'item', 20, 100, 10);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (26, 'item', 21, 100, 10);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (27, 'item', 22, 100, 10);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (28, 'item', 23, 100, 10);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (29, 'item', 24, 100, 10);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (30, 'item', 25, 100, 10);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (31, 'item', 26, 100, 10);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (32, 'item', 27, 100, 10);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (33, 'item', 28, 100, 10);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (34, 'item', 29, 100, 10);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (35, 'item', 30, 100, 10);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (36, 'item', 31, 100, 10);



INSERT INTO coupon (code, discount_percentage, description, expiry_date, used) VALUES ('ABC123', 2, '2% discount on subtotal', '2025-10-04', false);
INSERT INTO coupon (code, discount_percentage, description, expiry_date, used) VALUES ('DEF456', 5, '5% discount on subtotal', '2025-10-04', false);
INSERT INTO coupon (code, discount_percentage, description, expiry_date, used) VALUES ('OPQ789', 10, '10% discount on subtotal', '2025-10-04', false);

INSERT INTO shipping_method (name, fee, discount_fee) VALUES ('standard', 17.95, 0);
INSERT INTO shipping_method (name, fee, discount_fee) VALUES ('express', 22.95, 9.95);
