SELECT * FROM customer;
SELECT * FROM public.order;
SELECT * FROM order_item;
SELECT * FROM bag;
SELECT * FROM item;
SELECT * FROM preselection;
SELECT * FROM shipment;
SELECT * FROM shipping_method;
SELECT * FROM coupon;
SELECT * FROM inventory ORDER BY id;
SELECT * FROM inventory_transaction;

DROP TABLE order_item cascade;
DROP TABLE public.order cascade;
DROP TABLE customer cascade;
DROP TABLE shipment cascade;
DROP TABLE shipping_method cascade;
DROP TABLE inventory_transaction cascade;
DROP TABLE inventory cascade;
DROP TABLE coupon cascade;
DROP TABLE preselection cascade;
DROP TABLE item cascade;
DROP TABLE bag cascade;
Truncate alembic_version;

INSERT INTO bag (id, image_url, video_url, name, description, price) VALUES (1, 'https://giftoz.netlify.app/images/custom/bag1.jpeg', NULL, 'Pompompurin bag', 'bag', 1);
INSERT INTO bag (id, image_url, video_url, name, description, price) VALUES (2, 'https://giftoz.netlify.app/images/custom/bag2.jpeg', NULL, 'Hello Kitty bag', 'bag', 1);
INSERT INTO bag (id, image_url, video_url, name, description, price) VALUES (3, 'https://giftoz.netlify.app/images/custom/bag3.jpeg', NULL, 'Kuromi bag', 'bag', 1);
INSERT INTO bag (id, image_url, video_url, name, description, price) VALUES (4, 'https://giftoz.netlify.app/images/custom/bag4.jpeg', NULL, 'Cinnamoroll bag', 'bag', 1);
INSERT INTO bag (id, image_url, video_url, name, description, price) VALUES (5, 'https://giftoz.netlify.app/images/custom/bag5.jpeg', NULL, 'My Melody bag', 'bag', 1);

INSERT INTO item (id, image_url, video_url, product, name, description, price) VALUES (1, 'https://giftoz.netlify.app/images/custom/bricks1.jpeg', NULL, 'bricks', 'bricks1', 'bricks', 2.5);
INSERT INTO item (id, image_url, video_url, product, name, description, price) VALUES (2, 'https://giftoz.netlify.app/images/custom/bricks2.jpeg', NULL, 'bricks', 'bricks2', 'bricks', 2.5);
INSERT INTO item (id, image_url, video_url, product, name, description, price) VALUES (3, 'https://giftoz.netlify.app/images/custom/bricks3.jpeg', NULL, 'bricks', 'bricks3', 'bricks', 2.5);
INSERT INTO item (id, image_url, video_url, product, name, description, price) VALUES (4, 'https://giftoz.netlify.app/images/custom/bricks4.jpeg', NULL, 'bricks', 'bricks4', 'bricks', 2.5);
INSERT INTO item (id, image_url, video_url, product, name, description, price) VALUES (5, 'https://giftoz.netlify.app/images/custom/bricks5.jpeg', NULL, 'bricks', 'bricks5', 'bricks', 2.5);
INSERT INTO item (id, image_url, video_url, product, name, description, price) VALUES (6, 'https://giftoz.netlify.app/images/custom/bricks6.jpeg', NULL, 'bricks', 'bricks6', 'bricks', 2.5);
INSERT INTO item (id, image_url, video_url, product, name, description, price) VALUES (7, 'https://giftoz.netlify.app/images/custom/bricks7.jpeg', NULL, 'bricks', 'bricks7', 'bricks', 2.5);
INSERT INTO item (id, image_url, video_url, product, name, description, price) VALUES (8, 'https://giftoz.netlify.app/images/custom/bricks8.jpeg', NULL, 'bricks', 'bricks8', 'bricks', 2.5);
INSERT INTO item (id, image_url, video_url, product, name, description, price) VALUES (9, 'https://giftoz.netlify.app/images/custom/bricks9.jpeg', NULL, 'bricks', 'bricks9', 'bricks', 2.5);
INSERT INTO item (id, image_url, video_url, product, name, description, price) VALUES (10, 'https://giftoz.netlify.app/images/custom/bricks10.jpeg', NULL, 'bricks', 'bricks10', 'bricks', 2.5);
INSERT INTO item (id, image_url, video_url, product, name, description, price) VALUES (11, 'https://giftoz.netlify.app/images/custom/bricks11.jpeg', NULL, 'bricks', 'bricks11', 'bricks', 2.5);
INSERT INTO item (id, image_url, video_url, product, name, description, price) VALUES (51, 'https://giftoz.netlify.app/images/custom/design_ruler1.jpeg', NULL, 'design_ruler', 'design ruler1', 'design ruler', 1);
INSERT INTO item (id, image_url, video_url, product, name, description, price) VALUES (52, 'https://giftoz.netlify.app/images/custom/design_ruler2.jpeg', NULL, 'design_ruler', 'design ruler2', 'design ruler', 1);
INSERT INTO item (id, image_url, video_url, product, name, description, price) VALUES (53, 'https://giftoz.netlify.app/images/custom/design_ruler3.jpeg', NULL, 'design_ruler', 'design ruler3', 'design ruler', 1);
INSERT INTO item (id, image_url, video_url, product, name, description, price) VALUES (54, 'https://giftoz.netlify.app/images/custom/design_ruler4.jpeg', NULL, 'design_ruler', 'design ruler4', 'design ruler', 1);
INSERT INTO item (id, image_url, video_url, product, name, description, price) VALUES (101, 'https://giftoz.netlify.app/images/custom/id_holder1.jpeg', NULL, 'id_holder', 'id holder1', 'id holder', 2.5);
INSERT INTO item (id, image_url, video_url, product, name, description, price) VALUES (102, 'https://giftoz.netlify.app/images/custom/id_holder2.jpeg', NULL, 'id_holder', 'id holder2', 'id holder', 2.5);
INSERT INTO item (id, image_url, video_url, product, name, description, price) VALUES (103, 'https://giftoz.netlify.app/images/custom/id_holder3.jpeg', NULL, 'id_holder', 'id holder3', 'id holder', 2.5);
INSERT INTO item (id, image_url, video_url, product, name, description, price) VALUES (104, 'https://giftoz.netlify.app/images/custom/id_holder4.jpeg', NULL, 'id_holder', 'id holder4', 'id holder', 2.5);
INSERT INTO item (id, image_url, video_url, product, name, description, price) VALUES (105, 'https://giftoz.netlify.app/images/custom/id_holder5.jpeg', NULL, 'id_holder', 'id holder5', 'id holder', 2.5);
INSERT INTO item (id, image_url, video_url, product, name, description, price) VALUES (106, 'https://giftoz.netlify.app/images/custom/id_holder6.jpeg', NULL, 'id_holder', 'id holder6', 'id holder', 2.5);
INSERT INTO item (id, image_url, video_url, product, name, description, price) VALUES (151, 'https://giftoz.netlify.app/images/custom/pencil_sharpener1.jpeg', NULL, 'pencil_sharpener', 'pencil sharpener1', 'pencil sharpener', 3);
INSERT INTO item (id, image_url, video_url, product, name, description, price) VALUES (152, 'https://giftoz.netlify.app/images/custom/pencil_sharpener2.jpeg', NULL, 'pencil_sharpener', 'pencil sharpener2', 'pencil sharpener', 3);
INSERT INTO item (id, image_url, video_url, product, name, description, price) VALUES (201, 'https://giftoz.netlify.app/images/custom/bracelet1.jpeg', NULL, 'bracelet', 'bracelet1', 'bracelet', 2);
INSERT INTO item (id, image_url, video_url, product, name, description, price) VALUES (202, 'https://giftoz.netlify.app/images/custom/bracelet2.jpeg', NULL, 'bracelet', 'bracelet2', 'bracelet', 2);
INSERT INTO item (id, image_url, video_url, product, name, description, price) VALUES (251, 'https://giftoz.netlify.app/images/custom/squishy1.jpeg', NULL, 'squishy', 'squishy1', 'squishy', 1);
INSERT INTO item (id, image_url, video_url, product, name, description, price) VALUES (252, 'https://giftoz.netlify.app/images/custom/squishy2.jpeg', NULL, 'squishy', 'squishy2', 'squishy', 1);
INSERT INTO item (id, image_url, video_url, product, name, description, price) VALUES (253, 'https://giftoz.netlify.app/images/custom/squishy3.jpeg', NULL, 'squishy', 'squishy3', 'squishy', 1);
INSERT INTO item (id, image_url, video_url, product, name, description, price) VALUES (254, 'https://giftoz.netlify.app/images/custom/squishy4.jpeg', NULL, 'squishy', 'squishy4', 'squishy', 1);
INSERT INTO item (id, image_url, video_url, product, name, description, price) VALUES (255, 'https://giftoz.netlify.app/images/custom/squishy5.jpeg', NULL, 'squishy', 'squishy5', 'squishy', 1);
INSERT INTO item (id, image_url, video_url, product, name, description, price) VALUES (256, 'https://giftoz.netlify.app/images/custom/squishy6.jpeg', NULL, 'squishy', 'squishy6', 'squishy', 1);

INSERT INTO preselection (id, image_url, name, gender, description, price, bag_id, item_ids) VALUES (1, 'https://giftoz.netlify.app/images/preselections/preselection1.jpeg', 'Hello Kitty bag', 'girls', 'Preselection gift bag 1', 11, 2, '{151, 105, 252, 2, 51}');
INSERT INTO preselection (id, image_url, name, gender, description, price, bag_id, item_ids) VALUES (2, 'https://giftoz.netlify.app/images/preselections/preselection2.jpeg', 'Cinnamoroll bag', 'boys', 'Preselection gift bag 2', 12, 4, '{152, 104, 8, 52, 201}');
INSERT INTO preselection (id, image_url, name, gender, description, price, bag_id, item_ids) VALUES (3, 'https://giftoz.netlify.app/images/preselections/preselection3.jpeg', 'Pompompurin bag', 'boys', 'Preselection gift bag 3', 12, 1, '{152, 101, 253, 7, 202}');
INSERT INTO preselection (id, image_url, name, gender, description, price, bag_id, item_ids) VALUES (4, 'https://giftoz.netlify.app/images/preselections/preselection4.jpeg', 'My Melody bag', 'girls', 'Preselection gift bag 4', 11, 5, '{151, 103, 254, 2, 51}');
INSERT INTO preselection (id, image_url, name, gender, description, price, bag_id, item_ids) VALUES (5, 'https://giftoz.netlify.app/images/preselections/preselection5.jpeg', 'Kuromi bag', 'girls', 'Preselection gift bag 5', 10, 3, '{106, 251, 10, 53, 202}');

INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (1, 'bag', 1, 500, 50);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (2, 'bag', 2, 500, 50);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (3, 'bag', 3, 500, 50);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (4, 'bag', 4, 500, 50);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (5, 'bag', 5, 500, 50);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (6, 'item', 1, 100, 10);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (7, 'item', 2, 100, 10);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (8, 'item', 3, 100, 10);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (9, 'item', 4, 100, 10);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (10, 'item', 5, 100, 10);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (11, 'item', 6, 100, 10);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (12, 'item', 7, 100, 10);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (13, 'item', 8, 100, 10);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (14, 'item', 9, 100, 10);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (15, 'item', 10, 100, 10);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (16, 'item', 11, 100, 10);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (17, 'item', 51, 100, 10);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (18, 'item', 52, 100, 10);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (19, 'item', 53, 100, 10);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (20, 'item', 54, 100, 10);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (21, 'item', 101, 100, 10);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (22, 'item', 102, 100, 10);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (23, 'item', 103, 100, 10);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (24, 'item', 104, 100, 10);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (25, 'item', 105, 100, 10);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (26, 'item', 106, 100, 10);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (27, 'item', 151, 100, 10);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (28, 'item', 152, 100, 10);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (29, 'item', 201, 100, 10);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (30, 'item', 202, 100, 10);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (31, 'item', 251, 100, 10);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (32, 'item', 252, 100, 10);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (33, 'item', 253, 100, 10);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (34, 'item', 254, 100, 10);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (35, 'item', 255, 100, 10);
INSERT INTO inventory (id, entity_type, entity_id, current_stock, low_stock_threshold) VALUES (36, 'item', 256, 100, 10);


INSERT INTO coupon (code, discount_percentage, description, expiry_date, used) VALUES ('ABC123', 2, '2% discount on subtotal', '2025-10-04', false);
INSERT INTO coupon (code, discount_percentage, description, expiry_date, used) VALUES ('DEF456', 5, '5% discount on subtotal', '2025-10-04', false);
INSERT INTO coupon (code, discount_percentage, description, expiry_date, used) VALUES ('OPQ789', 10, '10% discount on subtotal', '2025-10-04', false);

INSERT INTO shipping_method (name, fee, discount_fee) VALUES ('standard', 17.95, 0);
INSERT INTO shipping_method (name, fee, discount_fee) VALUES ('express', 22.95, 9.95);
